[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
description = "A crate to play with the STM32F3DISCOVERY"
documentation = "https://docs.rs/f3"
keywords = ["arm", "cortex-m", "stm32f3discovery", "stm32"]
license = "MIT OR Apache-2.0"
name = "f3"
repository = "https://github.com/japaric/f3"
version = "0.3.0"

[dependencies]
cortex-m = "0.1.3"
ref_slice = "1.1.1"
stm32f30x-memory-map = "0.1.0"

[dependencies.compiler-builtins-snapshot]
features = ["memcpy"]
version = "0.0.20161008"

[dependencies.r0]
optional = true
version = "0.1.0"

[dev-dependencies]
m = "0.1.0"

[features]
default = ["default-exception-handler", "default-init", "default-panic-fmt", "examples", "interrupts", "static-ram"]
default-exception-handler = []
default-init = []
default-panic-fmt = []
examples = []
interrupts = []
static-ram = ["r0"]

[profile.release]
lto = true
