[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Board Support Crate for the STM32F3DISCOVERY"
documentation = "https://docs.rs/f3"
keywords = ["arm", "cortex-m", "stm32"]
license = "MIT OR Apache-2.0"
name = "f3"
repository = "https://github.com/japaric/f3"
version = "0.5.1"

[dependencies]
l3gd20 = "0.1.0"
lsm303dlhc = "0.1.0"
stm32f30x-hal = "0.1.0"

[dev-dependencies]
cortex-m = "0.4.1"
cortex-m-semihosting = "0.2.0"
cortex-m-rtfm = "0.3.1"

[dev-dependencies.nb]
features = ["unstable"]
version = "0.1.1"

[dev-dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.12"

[dev-dependencies.stm32f30x]
features = ["rt"]
version = "0.6.0"

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
